// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe-6ahJNjNAsMAAWqx1_Ip_0uAsvGRVrw',
    appId: '1:906959324206:web:770accc406f56e3814cbbf',
    messagingSenderId: '906959324206',
    projectId: 'restauranteb-c72fb',
    authDomain: 'restauranteb-c72fb.firebaseapp.com',
    storageBucket: 'restauranteb-c72fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfj-jzR2YwdoLonTYWtJiZkx6DlrUP-lE',
    appId: '1:906959324206:android:1da8cb3b17f3cea814cbbf',
    messagingSenderId: '906959324206',
    projectId: 'restauranteb-c72fb',
    storageBucket: 'restauranteb-c72fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-FQvqhu_s0s5eC8CEw-PasdzgJ9UGb2c',
    appId: '1:906959324206:ios:d3aaf3e2704e8b8314cbbf',
    messagingSenderId: '906959324206',
    projectId: 'restauranteb-c72fb',
    storageBucket: 'restauranteb-c72fb.appspot.com',
    iosBundleId: 'com.example.actividad3Dmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-FQvqhu_s0s5eC8CEw-PasdzgJ9UGb2c',
    appId: '1:906959324206:ios:d3aaf3e2704e8b8314cbbf',
    messagingSenderId: '906959324206',
    projectId: 'restauranteb-c72fb',
    storageBucket: 'restauranteb-c72fb.appspot.com',
    iosBundleId: 'com.example.actividad3Dmi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe-6ahJNjNAsMAAWqx1_Ip_0uAsvGRVrw',
    appId: '1:906959324206:web:f6554fe29e9c0ab914cbbf',
    messagingSenderId: '906959324206',
    projectId: 'restauranteb-c72fb',
    authDomain: 'restauranteb-c72fb.firebaseapp.com',
    storageBucket: 'restauranteb-c72fb.appspot.com',
  );
}
